module.exports = [{
    "id": 1,
    "nombre": "Thị Trấn Cẩm Thủy",
    "poblacion": 1706,
    "capital_pro": false,
    "capital_ca": false,
    "fk_provincia": 8
  }, {
    "id": 2,
    "nombre": "Az Zuwaytīnah",
    "poblacion": 6122,
    "capital_pro": true,
    "capital_ca": true,
    "fk_provincia": 16
  }, {
    "id": 3,
    "nombre": "Sumberkemuning",
    "poblacion": 9580,
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 29
  }, {
    "id": 4,
    "nombre": "Seixal",
    "poblacion": 4315,
    "cp": "2840-466",
    "capital_pro": false,
    "capital_ca": false,
    "fk_provincia": 28
  }, {
    "id": 5,
    "nombre": "Stanisław Dolny",
    "poblacion": 1503,
    "cp": "34-143",
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 27
  }, {
    "id": 6,
    "nombre": "Chengbei",
    "poblacion": 1998,
    "capital_pro": true,
    "capital_ca": true,
    "fk_provincia": 22
  }, {
    "id": 7,
    "nombre": "Shatrovo",
    "poblacion": 3854,
    "cp": "641960",
    "capital_pro": true,
    "capital_ca": true,
    "fk_provincia": 8
  }, {
    "id": 8,
    "nombre": "Créteil",
    "poblacion": 9945,
    "cp": "94024 CEDEX",
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 7
  }, {
    "id": 9,
    "nombre": "Yerba Buena",
    "poblacion": 8554,
    "cp": "4622",
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 3
  }, {
    "id": 10,
    "nombre": "Fujia",
    "poblacion": 2819,
    "capital_pro": true,
    "capital_ca": true,
    "fk_provincia": 12
  }, {
    "id": 11,
    "nombre": "Cisalak",
    "poblacion": 6388,
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 16
  }, {
    "id": 12,
    "nombre": "Selasari",
    "poblacion": 3127,
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 26
  }, {
    "id": 13,
    "nombre": "Najd al Jumā‘ī",
    "poblacion": 6522,
    "capital_pro": false,
    "capital_ca": false,
    "fk_provincia": 23
  }, {
    "id": 14,
    "nombre": "Niaohe",
    "poblacion": 3227,
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 16
  }, {
    "id": 15,
    "nombre": "Yartsevo",
    "poblacion": 8422,
    "cp": "215807",
    "capital_pro": true,
    "capital_ca": true,
    "fk_provincia": 17
  }, {
    "id": 16,
    "nombre": "Kulunda",
    "poblacion": 6527,
    "cp": "249070",
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 16
  }, {
    "id": 17,
    "nombre": "Satka",
    "poblacion": 4347,
    "cp": "456918",
    "capital_pro": false,
    "capital_ca": false,
    "fk_provincia": 8
  }, {
    "id": 18,
    "nombre": "Mulan",
    "poblacion": 5566,
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 30
  }, {
    "id": 19,
    "nombre": "Mošorin",
    "poblacion": 8656,
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 6
  }, {
    "id": 20,
    "nombre": "Arys",
    "poblacion": 8320,
    "capital_pro": false,
    "capital_ca": false,
    "fk_provincia": 30
  }, {
    "id": 21,
    "nombre": "Hila",
    "poblacion": 6379,
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 22
  }, {
    "id": 22,
    "nombre": "Moncton",
    "poblacion": 7047,
    "cp": "E1C",
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 18
  }, {
    "id": 23,
    "nombre": "Kibuku",
    "poblacion": 5341,
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 13
  }, {
    "id": 24,
    "nombre": "Daixi",
    "poblacion": 7008,
    "capital_pro": false,
    "capital_ca": false,
    "fk_provincia": 14
  }, {
    "id": 25,
    "nombre": "Gayam",
    "poblacion": 5434,
    "capital_pro": true,
    "capital_ca": true,
    "fk_provincia": 15
  }, {
    "id": 26,
    "nombre": "Kvitok",
    "poblacion": 2767,
    "cp": "665081",
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 7
  }, {
    "id": 27,
    "nombre": "Kawangu",
    "poblacion": 4190,
    "capital_pro": false,
    "capital_ca": false,
    "fk_provincia": 27
  }, {
    "id": 28,
    "nombre": "Mafa",
    "poblacion": 3685,
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 26
  }, {
    "id": 29,
    "nombre": "Parachinar",
    "poblacion": 8006,
    "cp": "29051",
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 29
  }, {
    "id": 30,
    "nombre": "Jagna",
    "poblacion": 2734,
    "cp": "6308",
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 24
  }, {
    "id": 31,
    "nombre": "Daga",
    "poblacion": 2641,
    "capital_pro": false,
    "capital_ca": false,
    "fk_provincia": 5
  }, {
    "id": 32,
    "nombre": "Tiemen",
    "poblacion": 8385,
    "capital_pro": false,
    "capital_ca": false,
    "fk_provincia": 28
  }, {
    "id": 33,
    "nombre": "Lajarik",
    "poblacion": 4539,
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 7
  }, {
    "id": 34,
    "nombre": "Al Jīzah",
    "poblacion": 1252,
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 25
  }, {
    "id": 35,
    "nombre": "Pampas",
    "poblacion": 3711,
    "capital_pro": true,
    "capital_ca": true,
    "fk_provincia": 20
  }, {
    "id": 36,
    "nombre": "Pucacaca",
    "poblacion": 7953,
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 6
  }, {
    "id": 37,
    "nombre": "Morales",
    "poblacion": 1216,
    "cp": "134548",
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 19
  }, {
    "id": 38,
    "nombre": "Novhorod-Sivers’kyy",
    "poblacion": 3221,
    "capital_pro": true,
    "capital_ca": true,
    "fk_provincia": 10
  }, {
    "id": 39,
    "nombre": "Ornontowice",
    "poblacion": 8925,
    "cp": "43-178",
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 15
  }, {
    "id": 40,
    "nombre": "Mertert",
    "poblacion": 9329,
    "cp": "L-6693",
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 17
  }, {
    "id": 41,
    "nombre": "Naran Bulag",
    "poblacion": 8087,
    "capital_pro": true,
    "capital_ca": true,
    "fk_provincia": 20
  }, {
    "id": 42,
    "nombre": "Shreveport",
    "poblacion": 9511,
    "cp": "71105",
    "capital_pro": false,
    "capital_ca": false,
    "fk_provincia": 17
  }, {
    "id": 43,
    "nombre": "Karangkeng",
    "poblacion": 6453,
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 3
  }, {
    "id": 44,
    "nombre": "Shangyu",
    "poblacion": 8835,
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 23
  }, {
    "id": 45,
    "nombre": "Río Bueno",
    "poblacion": 6372,
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 6
  }, {
    "id": 46,
    "nombre": "Yilkiqi",
    "poblacion": 8942,
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 20
  }, {
    "id": 47,
    "nombre": "Itapemirim",
    "poblacion": 3085,
    "cp": "29330-000",
    "capital_pro": true,
    "capital_ca": true,
    "fk_provincia": 1
  }, {
    "id": 48,
    "nombre": "Gongyi",
    "poblacion": 9012,
    "capital_pro": false,
    "capital_ca": true,
    "fk_provincia": 3
  }, {
    "id": 49,
    "nombre": "El Perico",
    "poblacion": 2696,
    "capital_pro": false,
    "capital_ca": false,
    "fk_provincia": 29
  }, {
    "id": 50,
    "nombre": "Mosquée",
    "poblacion": 1650,
    "capital_pro": true,
    "capital_ca": false,
    "fk_provincia": 5
  }]